POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "vs",
    "important": true
}
# PUT http://localhost:3001/api/notes/68811cb582d1c6c65badac52
# Content-Type: application/json

# {
#   "content": "yes,Updated: VS Code makes backend testing easy!",
#   "important": false
# }
